linux:
  hosts:
    ft_onion_host:
      ansible_host: "{{ lookup('env', 'HOST_IP') }}"
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
    ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_PRIVATE_KEY_FILE') }}"
